// packages/react/src/components/ImmersiveScroll.tsx
import { useRef } from 'react';
import { ImmersiveScrollProvider } from '../context/ImmersiveScrollProvider';
import type { ImmersiveScrollProps } from '../types/component-props';
import { ImmersiveCanvas } from './ImmersiveCanvas';
import { ImmersiveDebugPanel } from './ImmersiveDebugPanel';
import { ImmersiveScrollbar } from './ImmersiveScrollbar';

export function ImmersiveScroll({
  video = null,
  framesPath = null,
  manifestPath = null,
  className,
  style,
  config,
  plugins,
  children,
  loadingFallback,
  errorFallback,
  overlay,
  scrollbarProps
}: ImmersiveScrollProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const viewportRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const shouldPinViewport = config?.trigger?.pin ?? true;

  return (
    <ImmersiveScrollProvider
      config={config}
      framesPath={framesPath}
      manifestPath={manifestPath}
      video={video}
      plugins={plugins}
      containerRef={containerRef}
      viewportRef={viewportRef}
      canvasRef={canvasRef}
    >
      <div
        ref={containerRef}
        className={className}
        style={{
          position: 'relative',
          minHeight: '100vh',
          overflow: 'hidden',
          background: '#000000',
          color: '#ffffff',
          ...style
        }}
      >
        <div
          ref={viewportRef}
          style={{
            position: shouldPinViewport ? 'sticky' : 'relative',
            top: 0,
            minHeight: '100vh',
            overflow: 'hidden'
          }}
        >
          <ImmersiveCanvas
            ref={canvasRef}
            style={{
              position: 'fixed',
              inset: 0,
              width: '100%',
              height: '100%',
              objectFit: 'cover'
            }}
          />
          {overlay}
          <ImmersiveScrollbar {...scrollbarProps} />
          {config?.debug?.enabled ? <ImmersiveDebugPanel /> : null}
        </div>
        <div style={{ position: 'relative', zIndex: 1 }}>
          {children ?? loadingFallback ?? errorFallback}
        </div>
      </div>
    </ImmersiveScrollProvider>
  );
}

// packages/solid/src/components/ImmersiveScroll.tsx
import type { ParentProps } from 'solid-js';
import { createSignal } from 'solid-js';
import type {
  ImmersivePlugin,
  PartialImmersiveConfig
} from '@immersive-scroll/core';
import { ImmersiveContext } from '../context/ImmersiveContext';
import { createSolidEngineBinding } from '../interop/createSolidEngineBinding';
import { ImmersiveCanvas } from './ImmersiveCanvas';
import { ImmersiveScrollbar } from './ImmersiveScrollbar';

interface ImmersiveScrollProps extends ParentProps {
  config?: PartialImmersiveConfig;
  framesPath?: string | null;
  manifestPath?: string | null;
  video?: string | null;
  plugins?: ImmersivePlugin[];
  class?: string;
}

export function ImmersiveScroll(props: ImmersiveScrollProps) {
  const [container, setContainer] = createSignal<HTMLElement>();
  const [viewport, setViewport] = createSignal<HTMLElement>();
  const [canvas, setCanvas] = createSignal<HTMLCanvasElement>();
  const binding = createSolidEngineBinding(
    () => container(),
    () => viewport(),
    () => canvas(),
    props.config,
    props.framesPath,
    props.manifestPath,
    props.video,
    props.plugins ?? []
  );

  return (
    <ImmersiveContext.Provider value={binding}>
      <div
        ref={setContainer}
        class={props.class}
        style={{
          position: 'relative',
          overflow: 'hidden',
          'min-height': '100vh'
        }}
      >
        <div
          ref={setViewport}
          style={{
            position:
              props.config?.trigger?.pin === false ? 'relative' : 'sticky',
            top: '0',
            'min-height': '100vh',
            overflow: 'hidden'
          }}
        >
          <ImmersiveCanvas
            ref={setCanvas}
            style={{
              position: 'absolute',
              inset: '0',
              width: '100%',
              height: '100%'
            }}
          />
          <ImmersiveScrollbar />
        </div>
        <div style={{ position: 'relative', 'z-index': 1 }}>
          {props.children}
        </div>
      </div>
    </ImmersiveContext.Provider>
  );
}
